### ISSUE TITLE
User Review

### ISSUE THREAD

**Issue by edavidj** [OpenLiberty/draft-guide-reactive-service-testing#34]
Completion time: 30 minutes

**Notes**:

- Didn't investigate this error as I was still able to progress, but saw the following after running `mvn liberty:dev`.  
```
[INFO] [ERROR   ] CWMRX1004E: The Reactive Messaging Kafka Outgoing Connector received an error. The error is java.util.ServiceConfigurationError: javax.json.bind.spi.JsonbProvider: Provider org.eclipse.yasson.JsonBindingProvider not found
[INFO] 	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
[INFO] 	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
[INFO] 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
[INFO] 	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
[INFO] 	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
[INFO] 	at javax.json.bind.spi.JsonbProvider.provider(JsonbProvider.java:113)
[INFO] 	at javax.json.bind.JsonbBuilder.create(JsonbBuilder.java:108)
[INFO] 	at io.openliberty.guides.models.SystemLoad.<clinit>(SystemLoad.java:25)
[INFO] 	at io.openliberty.guides.system.SystemService.lambda$sendSystemLoad$0(SystemService.java:50)
[INFO] 	at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:64)
[INFO] 	at io.reactivex.rxjava3.internal.operators.flowable.FlowableInterval$IntervalSubscriber.run(FlowableInterval.java:93)
[INFO] 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectPeriodicTask.run(ScheduledDirectPeriodicTask.java:39)
[INFO] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[INFO] 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
[INFO] 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
[INFO] 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[INFO] 	at java.lang.Thread.run(Thread.java:748)
[INFO] .
[INFO] [ERROR   ] CWMRX1003E: An error occurred when sending a message to the Kafka broker. The error is: org.apache.kafka.common.errors.TimeoutException: Topic systemLoadTopic not present in metadata after 60000 ms.
[INFO] .
```
- Maybe I'm misunderstanding the context but in the `Testing your containers` section there's a line `Kafka has its own default deserializer, however, a customer deserializer has been provided...`, is this meant to say `custom deserializer`?

- Got the following error after pressing `enter/return` post adding `SystemServiceIT.java`. Was resolved after restarting dev mode. May have been issue on my end.
```
[ERROR] it.io.openliberty.guides.system.SystemServiceIT  Time elapsed: 41.714 s  <<< ERROR!
java.util.concurrent.CompletionException: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for URL to be accessible (http://192.168.43.109:9083/health/ready should return HTTP 200)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:708)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for URL to be accessible (http://192.168.43.109:9083/health/ready should return HTTP 200)
	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:214)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:876)
	at org.microshed.testing.testcontainers.ApplicationContainer.doStart(ApplicationContainer.java:277)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:302)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705)
	... 5 more
```
- For the final test got the following once, but didn't repeat after rerunning the tests several more times.
```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 19.141 s <<< FAILURE! - in it.io.openliberty.guides.inventory.InventoryServiceIT
[ERROR] testCpuUsage  Time elapsed: 5.817 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <2> but was: <1>
	at it.io.openliberty.guides.inventory.InventoryServiceIT.testCpuUsage(InventoryServiceIT.java:52)
```

**Clarity**:

- Content was well organized and easy to understand, like the restaurant example for async at the beginning. No issues.

**Comment by MaiHameed** [comment]
The errors regarding Kafka connectors should have been resolved with the latest commits to the `startContainers.sh` scripts.
